# Generated by Django 4.2.7 on 2023-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(help_text='Идентификатор организации в БД', primary_key=True, serialize=False)),
                ('full_name', models.TextField(help_text='Полное наименование организации', verbose_name='Полное наименование')),
                ('short_name', models.TextField(blank=True, help_text='Сокращенное наименование организации', null=True, verbose_name='Сокращенное наименование')),
                ('inn', models.CharField(blank=True, db_index=True, help_text='ИНН организации', max_length=12, null=True, verbose_name='ИНН')),
                ('factual_address', models.TextField(help_text='Адрес местонахождения организации', verbose_name='Адрес')),
                ('region_code', models.CharField(help_text='Код региона в соответствии со справочником ФНС России', max_length=3, null=True, verbose_name='Код региона')),
                ('date_added', models.DateTimeField(auto_now=True, help_text='Дата внесения организации в БД')),
                ('longitude', models.FloatField(help_text='Долгота расположения организации', verbose_name='Долгота')),
                ('latitude', models.FloatField(help_text='Широта расположения организации', verbose_name='Широта')),
                ('site', models.CharField(help_text='Сайт организации', max_length=100, null=True, verbose_name='Сайт организации')),
                ('email', models.EmailField(help_text='E-mail организации', max_length=100, null=True, verbose_name='E-mail организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
