# Generated by Django 4.2.7 on 2023-12-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('code', models.CharField(max_length=8,
                                          primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('skill', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['full_name'],
                     'verbose_name': 'Организация',
                     'verbose_name_plural': 'Организации'},
        ),
    ]
