# Generated by Django 4.2.7 on 2023-12-03 07:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_specialty_alter_organization_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресение')], verbose_name='День недели')),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=2), size=None, verbose_name='Часы работы')),
                ('day_type', models.CharField(choices=[('weekday', 'выходной'), ('holiday', 'праздник'), ('daily', 'будни')], max_length=30, verbose_name='Тип дня')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='organizations.organization')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organizations.specialty')),
            ],
        ),
    ]
