# Generated by Django 4.2.7 on 2023-12-03 11:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_specialty_alter_organization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='date_added',
            field=models.DateTimeField(auto_now=True, help_text='Дата внесения организации в БД', verbose_name='Дата создания организации в БД'),
        ),
        migrations.CreateModel(
            name='OrganizationSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресение')], verbose_name='День недели')),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None, verbose_name='Часы работы')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='organizations.organization', verbose_name='Организация')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organizations.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Расписание специальностей',
                'verbose_name_plural': 'Расписания специальностей',
                'ordering': None,
            },
        ),
        migrations.AddConstraint(
            model_name='organizationspecialty',
            constraint=models.UniqueConstraint(fields=('organization', 'specialty', 'day_of_the_week'), name='unique_orgspec_organization_specialty_day'),
        ),
    ]
