# Generated by Django 4.2.7 on 2023-12-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_addes_specialties'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationspecialty',
            name='unique_orgspec_organization_specialty_day',
        ),
        migrations.RemoveField(
            model_name='organizationspecialty',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='organizationspecialty',
            name='from_hour',
            field=models.TimeField(default='09:00', help_text='Время начала работы врача', verbose_name='Время начала работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationspecialty',
            name='to_hour',
            field=models.TimeField(default='18:00', help_text='Время окончания работы врача', verbose_name='Время окончания работы'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='organizationspecialty',
            constraint=models.UniqueConstraint(fields=('organization', 'specialty', 'day_of_the_week'), name='organizations_unique_orgspec_schedule'),
        ),
    ]
