# Generated by Django 4.2.7 on 2023-12-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_added_from_to_hour_deleted_array'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['short_name', 'factual_address'], name='organizatio_short_n_32d8d1_idx'),
        ),
    ]
