# Generated by Django 4.2.7 on 2023-12-25 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_fill_doctor_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресение')], help_text='Номер дня недели', verbose_name='Номер дня недели')),
                ('from_hour', models.TimeField(help_text='Время начала работы организации', verbose_name='Время начала работы')),
                ('to_hour', models.TimeField(help_text='Время окончания работы организации', verbose_name='Время окончания работы')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Рабочие часы организации',
                'verbose_name_plural': 'Рабочие часы организаций',
                'ordering': None,
            },
        ),
        migrations.AddConstraint(
            model_name='organizationbusinesshour',
            constraint=models.UniqueConstraint(fields=('organization', 'day'), name='unique_org_day'),
        ),
    ]
