# Generated by Django 4.2.7 on 2024-01-03 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_added_index_org_short_name_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now=True, help_text='Дата и время создания записи пациента', verbose_name='Дата и время создания записи пациента')),
                ('datetime_start', models.DateTimeField(help_text='Дата и время начала записи пациента', verbose_name='Дата и время начала записи пациента')),
                ('status', models.CharField(choices=[('free', 'Свободна'), ('planned', 'Запланирована'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена'), ('finished', 'Завершена')], default='free', help_text='Статус записи', verbose_name='Статус записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='organizations.organization', verbose_name='Организация')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='organizations.specialty', verbose_name='Специальность врача')),
            ],
        ),
    ]
