# Generated by Django 4.2.7 on 2024-01-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_changed_max_lenth_field_org_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['skill'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(help_text='Идентификатор талончика', primary_key=True, serialize=False),
        ),
    ]
