version: '3.4'
services:
  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_dt:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "28962:80"
    volumes:
      - ./nginx/default_local.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build:
      context: ../backend
    hostname: worker
    entrypoint: celery
    command: -A backend worker -l INFO
    links:
      - redis
    depends_on:
      - redis
    env_file:
      - ./.env

volumes:
  postgres_dt:
  static_value:
  media_value: