# Generated by Django 4.2.7 on 2024-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('text',
                 models.TextField(
                     max_length=500, verbose_name='Текст отзыва')),
                ('score', models.IntegerField(
                    choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                    verbose_name='Оценка организации')),
                ('pub_date', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата публикации отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-pub_date'],
            },
        ),
    ]
