# Generated by Django 4.2.7 on 2024-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('code', models.CharField(help_text='Код специальности', max_length=8, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(help_text='Наименование специальности', max_length=150, verbose_name='Наименование')),
                ('skill', models.CharField(help_text='Наименование врача по специальности', max_length=150, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['skill'],
            },
        ),
    ]
